INSERT INTO sites VALUES (0, 'Parsippany HQ', '4 Gatehall Dr', 'Parsippany', 'NJ', '07054', '9734016500');
INSERT INTO sites VALUES (1, 'Crisco', '5204 Spring Grove Ave', 'Cincinnati', 'OH', '45217', '5134828000');
INSERT INTO sites VALUES (2, 'Clabber Girl', 'E Margaret Dr', 'Terre Haute', 'IN', '47803', '8122329446');
INSERT INTO sites VALUES (3, 'ACH', '2301 SE Tones Dr', 'Ankeny', 'IA', '50021', '5159652711');
INSERT INTO tech VALUES (0, 'Mohamed', 'Lead Network Engineer');
INSERT INTO tech VALUES (1, 'Mike', 'Support Engineer');
INSERT INTO tech VALUES (2, 'Zac', 'Tech Support');
INSERT INTO tech VALUES (3, 'Brian', 'Lead Engineering');
INSERT INTO locations VALUES (1, 0, 0);
INSERT INTO locations VALUES (2, 1, 1);
INSERT INTO locations VALUES (3, 0, 0);
INSERT INTO locations VALUES (4, 3, 3);
INSERT INTO locations VALUES (5, 3, 3);
INSERT INTO locations VALUES (6, 2, 2);
INSERT INTO locations VALUES (7, 1, 1);
INSERT INTO locations VALUES (8, 2, 2);
INSERT INTO locations VALUES (9, 0, 0);
INSERT INTO locations VALUES (10, 0, 0);
INSERT INTO locations VALUES (11, 1, 1);
INSERT INTO locations VALUES (12, 1, 1);
INSERT INTO locations VALUES (13, 2, 2);
INSERT INTO locations VALUES (14, 0, 0);
INSERT INTO locations VALUES (15, 2, 2);
INSERT INTO locations VALUES (16, 1, 1);
INSERT INTO locations VALUES (17, 0, 0);
INSERT INTO locations VALUES (18, 2, 2);
INSERT INTO locations VALUES (19, 1, 1);

